version: '3'
volumes:
  postgresql-data:
    driver: 'local'
  bundle:
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - "3000:3000"
  postgresql:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - '4567:4567'